root: ./

structure:  
    readme: README.md  
    summary: SUMMARY.md

redirects:  
    # BASICS
    basics/what-is-filecoin/overview/: basics/what-is-filecoin/README.md
    basics/interplanetary-consensus/overview/: basics/interplanetary-consensus/README.md

    # STORAGE PROVIDER
    storage-provider/basics/overview/: storage-provider/basics/README.md

    # NODES
    nodes/implementations/overview/: nodes/implementations/README.md

    # SMART CONTRACTS
    smart-contracts/fundamentals/overview/: nodes/implementations/README.md

    # NETWORKS
    networks/mainnet/details/: networks/mainnet/README.md
    networks/calibration/details/: networks/calibration/README.md
    networks/spacenet/details/: networks/spacenet/README.md
    networks/local-testnet/set-up/: networks/local-testnet/README.md

    # REFERENCE
    reference/general/overview/: reference/general/README.md
    reference/built-in-actors/overview/: reference/built-in-actors/README.md
    reference/json-rpc/introduction/: reference/json-rpc/README.md



    # LEGACY-DOCS REDIRECTS
    # ---------------------
    # BASICS/ASSETS
    networks/mainnet/add-to-metamask: basics/assets/metamask-setup
    networks/hyperspace/add-to-metamask: basics/assets/metamask-setup
    networks/calibration/add-to-metamask: basics/assets/metamask-setup
    fvm/how-tos/add-to-metamask: basics/assets/metamask-setup
    developers/smart-contracts/how-tos/add-to-metamask: basics/assets/metamask-setup
    smart-contracts/wallets/transfer-fil/: basics/assets/transfer-fil
    smart-contracts/wallets/fil-to-zero-x/: basics/assets/transfer-fil
    
    # BASICS/HOW-RETRIEVAL-WORKS
    /developers/storage-helpers/how-tos/retrieve-data/: basics/how-retrieval-works/basic-retrieval
    
    # BASICS/HOW-STORAGE-WORKS
	about-filecoin/why-filecoin: basics/how-storage-works/filecoin-and-ipfs
	developers/introduction/apps-and-filecoin: basics/how-storage-works/filecoin-and-ipfs
	store/overview/start-storing: filecoin-docs/basics/how-storage-works/filecoin-plus
    store/filecoin-plus/overview: filecoin-docs/basics/how-storage-works/filecoin-plus
    store/filecoin-plus: filecoin-docs/basics/how-storage-works/filecoin-plus
	developers/storage-helpers/overview: basics/how-storage-works/storage-onramps
    developers/storage-helpers/ceramic: basics/how-storage-works/storage-onramps
    developers/storage-helpers/estuary: basics/how-storage-works/storage-onramps
    developers/storage-helpers/nft-storage: basics/how-storage-works/storage-onramps
    developers/storage-helpers/starling: basics/how-storage-works/storage-onramps
    developers/storage-helpers/web3-storage: basics/how-storage-works/storage-onramps
    store: basics/how-storage-works/storage-onramps
    store/tools: basics/how-storage-works/storage-onramps
    store/tools/estuary: basics/how-storage-works/storage-onramps

	#BASICS/PROJECT-AND-COMMUNITY
	about-filecoin/chat-and-discussion-forums: basics/project-and-community/chat-and-discussion-forums
    community: basics/project-and-community/chat-and-discussion-forums
    community/chat-and-discussion-forums: basics/project-and-community/chat-and-discussion-forums
    about/community/chat-and-discussion-forums: basics/project-and-community/chat-and-discussion-forums
    about-filecoin/filecoin-compared-to: basics/project-and-community/filecoin-compared-to
    about/basics/filecoin-compared-to: basics/project-and-community/filecoin-compared-to
	about/basics/filecoin-faq/: basics/project-and-community/filecoin-faqs
	about-filecoin/related-projects: basics/project-and-community/related-projects
    project/related-projects: basics/project-and-community/related-projects
    about/project/related-projects: basics/project-and-community/related-projects
    about-filecoin/chat-and-discussion-forums: basics/project-and-community/social-media
    community/social-media: basics/project-and-community/social-media
    community/social-media/social-media: basics/project-and-community/social-media
    about-filecoin/social-media: basics/project-and-community/social-media
    about/community/social-media: basics/project-and-community/social-media
    about-filecoin/project: basics/project-and-community/the-filecoin-project
    project: basics/project-and-community/the-filecoin-project
    project/related-projects: basics/project-and-community/the-filecoin-project
    about/project/the-filecoin-project: basics/project-and-community/the-filecoin-project
    about-filecoin/ways-to-contribute: basics/project-and-community/ways-to-contribute
    community/contribute/ways-to-contribute: basics/project-and-community/ways-to-contribute
    about/contribute/ways-to-contribute: basics/project-and-community/ways-to-contribute
    about/contribute/contribution-tutorial: basics/project-and-community/ways-to-contribute
    about/contribute/grammar-and-formatting: basics/project-and-community/ways-to-contribute
    about/contribute/writing-guide: basics/project-and-community/ways-to-contribute




    

    # ---------------------


