root: ./

structure:
  readme: ./WELCOME.md
  summary: SUMMARY.md

redirects:
  about-filecoin/chat-and-discussion-forums: basics/project-and-community/chat-and-discussion-forums.md
  about-filecoin/filecoin-compared-to: basics/project-and-community/filecoin-compared-to.md
  about-filecoin/network-performance: networks/mainnet/network-performance.md
  about-filecoin/project: basics/project-and-community/the-filecoin-project.md
  about-filecoin/related-projects: basics/project-and-community/related-projects.md
  about-filecoin/social-media: basics/project-and-community/social-media.md
  about-filecoin/ways-to-contribute: basics/project-and-community/ways-to-contribute.md
  about-filecoin/why-filecoin: basics/how-storage-works/filecoin-and-ipfs.md
  about/basics/filecoin-compared-to: basics/project-and-community/filecoin-compared-to.md
  about/basics/filecoin-faq: basics/project-and-community/filecoin-faqs.md
  about/basics/how-filecoin-works: basics/what-is-filecoin/README.md
  about/basics/introduction: basics/what-is-filecoin/README.md
  about/basics/what-is-filecoin: basics/what-is-filecoin/README.md
  about/community/chat-and-discussion-forums: basics/project-and-community/chat-and-discussion-forums.md
  about/community/social-media: basics/project-and-community/social-media.md
  about/contribute/contribution-tutorial: basics/project-and-community/ways-to-contribute.md
  about/contribute/grammar-and-formatting: basics/project-and-community/ways-to-contribute.md
  about/contribute/ways-to-contribute: basics/project-and-community/ways-to-contribute.md
  about/contribute/writing-guide: basics/project-and-community/ways-to-contribute.md
  about/project/related-projects: basics/project-and-community/related-projects.md
  about/project/the-filecoin-project: basics/project-and-community/the-filecoin-project.md
  basics: basics/what-is-filecoin/README.md
  basics/interplanetary-consensus/overview: basics/interplanetary-consensus/README.md
  basics/the-blockchain/tipsets: basics/the-blockchain/blocks-and-tipsets.md
  basics/what-is-filecoin/overview: basics/what-is-filecoin/README.md
  build: smart-contracts/fundamentals/README.md
  build/developer-tools/wallets-signing-tools-api-clients: reference/general/README.md
  build/examples: smart-contracts/fundamentals/README.md
  build/examples/network-inspector/lotus-and-go-ipfs-interactions: smart-contracts/fundamentals/README.md
  build/examples/network-inspector/overview: smart-contracts/fundamentals/README.md
  build/examples/web-applications/overview: smart-contracts/fundamentals/README.md
  build/fvm/basics/tools: reference/general/tools.md
  build/get-building/overview: smart-contracts/fundamentals/README.md
  build/signing-libraries: reference/general/README.md
  community: basics/project-and-community/chat-and-discussion-forums.md
  community/chat-and-discussion-forums: basics/project-and-community/chat-and-discussion-forums.md
  community/contribute/ways-to-contribute: basics/project-and-community/ways-to-contribute.md
  community/social-media: basics/project-and-community/social-media.md
  community/social-media/social-media: basics/project-and-community/social-media.md
  developers/infrastructure/block-explorers: networks/mainnet/explorers.md
  developers/infrastructure/how-tos/run-a-local-network: networks/local-testnet.md
  developers/infrastructure/how-tos/spin-up-a-lite-node: nodes/lite-nodes/spin-up-a-lite-node.md
  developers/infrastructure/libraries: smart-contracts/developing-contracts/client-contract-tutorial.md
  developers/infrastructure/network-performance: networks/mainnet/network-performance.md
  developers/introduction/apps-and-filecoin: basics/how-storage-works/filecoin-and-ipfs.md
  developers/introduction/filecoin-and-ipfs: smart-contracts/fundamentals/the-fvm.md
  developers/introduction/overview: smart-contracts/fundamentals/the-fvm.md
  developers/reference/built-in-actors/account-actor: reference/built-in-actors/protocol-api.md
  developers/reference/built-in-actors/datacap: reference/built-in-actors/protocol-api.md
  developers/reference/built-in-actors/miner: reference/built-in-actors/protocol-api.md
  developers/reference/built-in-actors/multisig: reference/built-in-actors/protocol-api.md
  developers/reference/built-in-actors/storage-market-actor: reference/built-in-actors/protocol-api.md
  developers/reference/built-in-actors/storage-power-actor: reference/built-in-actors/protocol-api.md
  developers/reference/built-in-actors/verified-registry-actor: reference/built-in-actors/protocol-api.md
  developers/reference/json-rpc/auth: reference/json-rpc/auth.md
  developers/reference/json-rpc/beacon: reference/json-rpc/beacon.md
  developers/reference/json-rpc/chain: reference/json-rpc/chain.md
  developers/reference/json-rpc/create: reference/json-rpc/create.md
  developers/reference/json-rpc/eth: reference/json-rpc/eth.md
  developers/reference/json-rpc/gas: reference/json-rpc/gas.md
  developers/reference/json-rpc/i: reference/json-rpc/i.md
  developers/reference/json-rpc/introduction: reference/json-rpc/README.md
  developers/reference/json-rpc/log: reference/json-rpc/log.md
  developers/reference/json-rpc/market: reference/json-rpc/market.md
  developers/reference/json-rpc/miner: reference/json-rpc/miner.md
  developers/reference/json-rpc/mpool: reference/json-rpc/mpool.md
  developers/reference/json-rpc/msig: reference/json-rpc/msig.md
  developers/reference/json-rpc/net: reference/json-rpc/net.md
  developers/reference/json-rpc/paych: reference/json-rpc/paych.md
  developers/reference/json-rpc/state: reference/json-rpc/state.md
  developers/reference/json-rpc/sync: reference/json-rpc/sync.md
  developers/reference/json-rpc/wallet: reference/json-rpc/wallet.md
  developers/reference/specification: reference/general/specifications.md
  developers/reference/tools: reference/general/tools.md
  developers/smart-contracts/about/blueprints: smart-contracts/fundamentals/the-fvm.md
  developers/smart-contracts/about/faqs: smart-contracts/fundamentals/faqs.md
  developers/smart-contracts/about/project: smart-contracts/fundamentals/roadmap.md
  developers/smart-contracts/about/support: smart-contracts/fundamentals/support.md
  developers/smart-contracts/about/use-cases: smart-contracts/fundamentals/the-fvm.md
  developers/smart-contracts/concepts/accounts-and-assets: basics/the-blockchain/addresses.md
  developers/smart-contracts/concepts/actors-and-contracts: basics/the-blockchain/actors.md
  developers/smart-contracts/concepts/ethereum-compatibility: smart-contracts/filecoin-evm-runtime/difference-with-ethereum.md
  developers/smart-contracts/concepts/filecoin-evm: smart-contracts/fundamentals/filecoin-evm-runtime.md
  developers/smart-contracts/concepts/tipsets: basics/the-blockchain/blocks-and-tipsets.md
  developers/smart-contracts/filecoin-virtual-machine: smart-contracts/fundamentals/the-fvm.md
  developers/smart-contracts/hardhat: smart-contracts/developing-contracts/hardhat.md
  developers/smart-contracts/how-tos/add-to-metamask: basics/assets/metamask-setup.md
  developers/smart-contracts/how-tos/calculate-gas: smart-contracts/filecoin-evm-runtime/how-gas-works.md
  developers/smart-contracts/how-tos/deploy-a-contract: smart-contracts/developing-contracts/remix.md
  developers/smart-contracts/how-tos/future-proof: smart-contracts/developing-contracts/best-practices.md
  developers/smart-contracts/how-tos/get-test-tokens: smart-contracts/developing-contracts/get-test-tokens.md
  developers/smart-contracts/how-tos/use-a-faucet: smart-contracts/developing-contracts/get-test-tokens.md
  developers/smart-contracts/quickstart: smart-contracts/fundamentals/erc-20-quickstart.md
  developers/storage-helpers/ceramic: basics/how-storage-works/storage-onramps.md
  developers/storage-helpers/estuary: basics/how-storage-works/storage-onramps.md
  developers/storage-helpers/how-tos/retrieve-data: basics/how-retrieval-works/basic-retrieval.md
  developers/storage-helpers/nft-storage: basics/how-storage-works/storage-onramps.md
  developers/storage-helpers/overview: basics/how-storage-works/storage-onramps.md
  developers/storage-helpers/starling: basics/how-storage-works/storage-onramps.md
  developers/storage-helpers/web3-storage: basics/how-storage-works/storage-onramps.md
  fvm: smart-contracts/fundamentals/the-fvm.md
  fvm/basics/faqs: smart-contracts/fundamentals/faqs.md
  fvm/basics/quickstart: smart-contracts/fundamentals/erc-20-quickstart.md
  fvm/basics/support: smart-contracts/fundamentals/support.md
  fvm/concepts/accounts-and-assets: basics/the-blockchain/addresses.md
  fvm/concepts/actors-and-contracts: basics/the-blockchain/actors.md
  fvm/concepts/tipsets: basics/the-blockchain/blocks-and-tipsets.md
  fvm/how-tos/add-to-metamask: basics/assets/metamask-setup.md
  fvm/how-tos/quickstart: smart-contracts/fundamentals/erc-20-quickstart.md
  fvm/how-tos/use-a-faucet: smart-contracts/developing-contracts/get-test-tokens.md
  fvm/reference/tools: reference/general/tools.md
  get-started: basics/what-is-filecoin/README.md
  get-started/explore-the-network: networks/mainnet/explorers.md
  get-started/overview: basics/what-is-filecoin/README.md
  get-started/overview/get-started: smart-contracts/fundamentals/README.md
  get-started/store-and-retrieve/setup: basics/what-is-filecoin/README.md
  glossary: reference/general/glossary.md
  intro/intro-to-filecoin/blockchain: basics/what-is-filecoin/blockchain.md
  intro/intro-to-filecoin/crypto-economics: basics/what-is-filecoin/crypto-economics.md
  intro/intro-to-filecoin/network: basics/what-is-filecoin/networks.md
  intro/intro-to-filecoin/programming-on-filecoin: basics/what-is-filecoin/programming-on-filecoin.md
  intro/intro-to-filecoin/retrieval-market: basics/what-is-filecoin/retrieval-market.md
  intro/intro-to-filecoin/storage-market: basics/what-is-filecoin/storage-market.md
  intro/intro-to-filecoin/storage-model: basics/what-is-filecoin/storage-model.md
  intro/intro-to-filecoin/what-is-filecoin: basics/what-is-filecoin/README.md
  mine: storage-providers/basics/README.md
  mine/connectivity: storage-providers/basics/README.md
  mine/mining-architectures: storage-providers/infrastructure/reference-architectures.md
  mine/slashing: storage-providers/filecoin-economics/slashing.md
  mine/spacerace: storage-providers/basics/README.md
  networks: networks/mainnet.md
  networks/calibration/add-to-metamask: basics/assets/metamask-setup.md
  networks/calibration/details: networks/calibration/README.md
  networks/hyperspace/add-to-metamask: basics/assets/metamask-setup.md
  networks/hyperspace/details: networks/calibration.md
  networks/hyperspace/explorers: networks/calibration/explorers.md
  networks/hyperspace/get-test-tokens: smart-contracts/developing-contracts/get-test-tokens.md
  networks/hyperspace/rpcs: networks/calibration/rpcs.md
  networks/local-testnet: networks/local-testnet.md
  networks/local-testnet/set-up: networks/local-testnet/README.md
  networks/mainnet: networks/mainnet.md
  networks/mainnet/add-to-metamask: basics/assets/metamask-setup.md
  networks/mainnet/details: networks/mainnet/README.md
  networks/network-performance: networks/mainnet/network-performance.md
  networks/overview: networks/mainnet.md
  networks/overview/network-performance: networks/mainnet/network-performance.md
  networks/spacenet: networks/deprecated-networks/README.md
  networks/spacenet/details: networks/deprecated-networks/README.md
  nodes/implementations/overview: nodes/implementations/README.md
  nodes/node-providers: nodes/full-nodes/node-providers.md
  nodes/node-providers/ankr: nodes/full-nodes/node-providers.md
  nodes/node-providers/chainstack: nodes/full-nodes/node-providers.md
  nodes/node-providers/glif: nodes/full-nodes/node-providers.md
  project: basics/project-and-community/the-filecoin-project.md
  project/related-projects: basics/project-and-community/related-projects.md
  reference: reference/general/README.md
  reference/built-in-actors: reference/built-in-actors.md
  reference/built-in-actors/overview: reference/built-in-actors/README.md
  reference/exchanges: reference/exchanges.md
  reference/general: reference/general/README.md
  reference/general/overview: reference/general/README.md
  reference/glossary: reference/general/glossary.md
  reference/json-rpc/introduction: reference/json-rpc/README.md
  reference/reference/glossary: reference/general/glossary.md
  reference/reference/overview: reference/general/README.md
  smart-contracts: smart-contracts/fundamentals/the-fvm.md
  smart-contracts/advanced/wfil: smart-contracts/advanced/wrapped-fil.md
  smart-contracts/developing-contracts: smart-contracts/developing-contracts/best-practices.md
  smart-contracts/filecoin-evm-runtime: smart-contracts/filecoin-evm-runtime/actor-types.md
  smart-contracts/fundamentals: smart-contracts/fundamentals/the-fvm.md
  smart-contracts/fundamentals/overview: nodes/implementations/README.md
  smart-contracts/wallets/fil-to-zero-x: basics/assets/transfer-fil.md
  smart-contracts/wallets/filforwader: smart-contracts/filecoin-evm-runtime/filforwarder.md
  smart-contracts/wallets/transfer-fil: basics/assets/transfer-fil.md
  storage-provider: storage-providers/basics/README.md
  storage-provider/architecture/lotus-automation: storage-providers/architecture/lotus-automation.md
  storage-provider/architecture/Lotus-components: storage-providers/architecture/lotus-components.md
  storage-provider/architectures: storage-providers/infrastructure/reference-architectures.md
  storage-provider/basics/overview: storage-providers/basics/README.md
  storage-provider/filecoin-deals/filecoin-programs: storage-providers/filecoin-deals/filecoin-programs.md
  storage-provider/overview: storage-providers/basics/README.md
  storage-provider/rewards/slashing: storage-providers/filecoin-economics/slashing.md
  storage-provider/slashing: storage-providers/filecoin-economics/slashing.md
  storage-provider/storage-provider-architectures: storage-providers/infrastructure/reference-architectures.md
  store: basics/how-storage-works/storage-onramps.md
  store/filecoin-plus: basics/how-storage-works/filecoin-plus.md
  store/filecoin-plus/overview: basics/how-storage-works/filecoin-plus.md
  store/overview/start-storing: basics/how-storage-works/filecoin-plus.md
  store/tools: basics/how-storage-works/storage-onramps.md
